const fs=require('fs'),vm=require('vm'),assert=require('assert');
function load(path){const c={console,globalThis:{__DEPULSE_TEST__:true},document:{querySelector(){return null},querySelectorAll(){return []}},window:{addEventListener(){}},fetch:async()=>({ok:false,status:404,text:async()=>'',json:async()=>({})}),EventSource:function(){},ResizeObserver:function(){this.observe=()=>{}},setInterval(){},setTimeout,clearTimeout,requestAnimationFrame:f=>f()};c.globalThis=c;c.__DEPULSE_TEST__=true;vm.createContext(c);vm.runInContext(fs.readFileSync(path,'utf8'),c);return c.DePulseLogic}
const baselineRenderer=process.env.DEPULSE_BASELINE_RENDERER||'renderer/qa/baseline-v14.3.7-renderer.js';
const base=load(baselineRenderer);
const next=load('renderer/renderer.js');
function bars(seed,n=260){const out=[];let p=40+(seed%140);for(let i=0;i<n;i++){const drift=((seed+i*17)%13-6)*.0015;p=Math.max(4,p*(1+drift));const spread=.006+((seed+i)%5)*.001;out.push({o:p*(1-spread/3),h:p*(1+spread),l:p*(1-spread),c:p,v:500000+((seed*997+i*1013)%3000000)});}return out}
function scenario(i){const now=Date.now(), sym='TST', px=25+(i%250)*1.7, cp=((i*37)%1200-600)/100, vix=12+((i*19)%2200)/100;const qs={TST:{price:px,changePercent:cp,previousClose:px/(1+cp/100),sessionClose:px*.997,priorSessionClose:px/(1+cp/100),updatedAt:now,providerTimestamp:now,source:'finnhub-websocket',dataState:'live'},SPY:{price:600,changePercent:((i*11)%500-250)/100,updatedAt:now},QQQ:{price:520,changePercent:((i*13)%600-300)/100,updatedAt:now},DIA:{price:450,changePercent:((i*7)%400-200)/100,updatedAt:now},IWM:{price:225,changePercent:((i*5)%700-350)/100,updatedAt:now},XLK:{price:250,changePercent:((i*17)%650-325)/100,updatedAt:now},TLT:{price:90,changePercent:((i*23)%300-150)/100,updatedAt:now},GLD:{price:300,changePercent:((i*29)%300-150)/100,updatedAt:now},SLV:{price:35,changePercent:0,updatedAt:now},USO:{price:80,changePercent:0,updatedAt:now},VIX:{price:vix,changePercent:((i*31)%1000-500)/100,updatedAt:now}};const bm={};for(const s of Object.keys(qs)){const b=bars(i+s.length);bm[s]={daily:b,intraday:b.slice(-120),weekly:b.filter((_,j)=>j%5===0)}}const state={version:'x',settings:{dataMode:'live',overnightDataMode:'auto',earningsPenalty:10,marketContext:15,signalProfile:['balanced','conservative','aggressive'][i%3],swingWatchlistId:'swing',dayWatchlistId:'day',longWatchlistId:'long',discoveryWatchlistId:'discovery',dayEnabled:true,swingEnabled:true,longEnabled:true},watchlists:[{id:'swing',name:'Swing',symbols:[sym]},{id:'day',name:'Day',symbols:[sym]},{id:'long',name:'Long',symbols:[sym]},{id:'discovery',name:'Discovery',symbols:[]}],ui:{selectedTicker:sym,scopeType:'watchlist',watchlistId:'swing'}};const runtime={status:'running',mode:'live',quotes:qs,bars:bm,history:{},fundamentals:{TST:{revenueGrowth:(i%50)-10,epsGrowth:(i%60)-15,roe:5+(i%30),netMargin:(i%25)-3,debtToEquity:20+(i%120),pe:10+(i%50),forwardPe:8+(i%45),freeCashFlow:1000000*(1+i%100)}},news:[],earnings:[],filings:[],secIntelligence:{},scanner:{mode:'day',status:'idle',results:[]},lastUpdated:{quotes:now,history:now,fundamentals:now,news:now,earnings:now,filings:now,vix:now},health:{},feed:{marketSession:['regular','pre-market','after-hours','closed'][i%4],feedState:'streaming',webSocketConnected:true,subscribedSymbols:[sym]}};return {state,runtime}}
function normalized(x){return JSON.parse(JSON.stringify(x))}
let checks=0;for(let i=0;i<801;i++){const sc=scenario(i);base.setState(sc.state,sc.runtime);next.setState(sc.state,sc.runtime);for(const h of ['day','swing','long']){const pa=base.planFor('TST',h),pb=next.planFor('TST',h),pick=p=>({score:p.score,direction:p.direction,tone:p.tone,families:p.families,entry:p.entry,target:p.target,invalid:p.invalid,rr:p.rr,atr:p.atr,rsi:p.rsi,rv:p.rv,rs:p.rs,sma20:p.sma20,sma50:p.sma50,sma200:p.sma200,vwap:p.vwap,support:p.support,resistance:p.resistance,eventRisk:p.eventRisk,quality:p.quality});const a=normalized(pick(pa)),b=normalized(pick(pb));try{assert.deepStrictEqual(b,a)}catch(e){console.error('Mismatch scenario',i,h,JSON.stringify(a),JSON.stringify(b));throw e}checks++}}
assert.equal(checks,2403);console.log(`deterministic trading equivalence ${checks}/${checks}: PASS`);
