const fs=require('fs'),vm=require('vm'),assert=require('assert');
const context={console,globalThis:{__DEPULSE_TEST__:true},document:{querySelector(){return null},querySelectorAll(){return []}},window:{addEventListener(){}},fetch:async()=>({ok:false,status:404,text:async()=>'',json:async()=>({})}),EventSource:function(){},ResizeObserver:function(){this.observe=()=>{}},setInterval(){},setTimeout,clearTimeout,requestAnimationFrame:f=>f()};
context.globalThis=context;context.__DEPULSE_TEST__=true;vm.createContext(context);vm.runInContext(fs.readFileSync('renderer/renderer.js','utf8'),context);
const L=context.DePulseLogic;
const htmlSource=fs.readFileSync('renderer/index.html','utf8'),cssSource=fs.readFileSync('renderer/styles.css','utf8'),rendererSource=fs.readFileSync('renderer/renderer.js','utf8'),mainSource=fs.readdirSync('.').filter(x=>x.endsWith('.go')&&!x.endsWith('_test.go')).map(x=>fs.readFileSync(x,'utf8')).join('\n');
const fnNames=[...rendererSource.matchAll(/\bfunction\s+([A-Za-z_$][\w$]*)\s*\(/g)].map(m=>m[1]),fnCounts=fnNames.reduce((m,n)=>(m[n]=(m[n]||0)+1,m),{});assert.deepEqual(Object.entries(fnCounts).filter(([,c])=>c>1),[], 'duplicate named renderer functions must be consolidated');
const releaseVersion=(rendererSource.match(/EXPECTED_RELEASE_VERSION='([^']+)'/)||[])[1],releaseBuild=(rendererSource.match(/EXPECTED_BUILD_ID='([^']+)'/)||[])[1];assert(releaseVersion&&releaseBuild,'canonical packaged release identity must be discoverable from renderer');

// Core technical calculations remain stable.
assert.equal(L.sma([1,2,3,4],2),3.5);assert(Math.abs(L.ema([1,2,3],2)-2.5555555556)<1e-6);assert(L.rsi([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],14)>99);
const bars=Array.from({length:30},(_,i)=>({o:100+i,h:102+i,l:99+i,c:101+i,v:1000+i*10}));assert(L.atr(bars,14)>0);assert(L.vwap(bars)>0);
const now=Date.now(),quotes={SPY:{price:600,changePercent:1,updatedAt:now},QQQ:{price:500,changePercent:1.2,updatedAt:now},DIA:{price:400,changePercent:.5,updatedAt:now},IWM:{price:220,changePercent:.8,updatedAt:now},XLK:{price:250,changePercent:1.1,updatedAt:now},TLT:{price:90,changePercent:-.2,updatedAt:now},GLD:{price:300,changePercent:-.1,updatedAt:now},SLV:{price:35,changePercent:-.1,updatedAt:now},USO:{price:80,changePercent:.2,updatedAt:now},VIX:{price:16.2,changePercent:-4,previousClose:16.88,updatedAt:now},AAA:{price:130,changePercent:1,previousClose:128,sessionClose:129.5,sessionCloseAt:now,priorSessionClose:128,updatedAt:now,providerTimestamp:now,source:'finnhub-websocket',dataState:'live'}};
const barMap={};for(const s of Object.keys(quotes))barMap[s]={daily:bars,intraday:bars,weekly:bars};
const state={version:releaseVersion,buildId:releaseBuild,settings:{dataMode:'live',overnightDataMode:'auto',aiProvider:'groq',groqModel:'openai/gpt-oss-120b',openRouterMode:'fast',openRouterSpecificModel:'openai/gpt-5.6-sol',geminiModel:'gemini-3.1-flash-lite',secEmail:'qa@example.com',autoStart:false,earningsPenalty:10,marketContext:15,signalProfile:'balanced',swingWatchlistId:'swing',dayWatchlistId:'day',longWatchlistId:'long',discoveryWatchlistId:'discovery',dayEnabled:true,swingEnabled:true,longEnabled:true},watchlists:[{id:'swing',name:'Swing Watchlist',symbols:['AAA']},{id:'day',name:'Day Trade Watchlist',symbols:['AAA']},{id:'long',name:'Long-Term Watchlist',symbols:['AAA']},{id:'discovery',name:'Discovery Watchlist',symbols:[]}],ui:{selectedTicker:'AAA',scopeType:'watchlist',watchlistId:'swing'},providerStatus:{},cacheInfo:{sizeBytes:2048,cachedSymbols:1,lastUpdated:now},lastCacheCleared:now-5000,configDir:'/tmp/depulse',cachePath:'/tmp/depulse/market-cache.json',maintenanceLastRun:0,hasFinnhubKey:false,hasAlpacaKey:false,hasAlpacaSecret:false,hasGroqKey:false,hasOpenRouterKey:false,hasGeminiKey:false,hasFREDKey:false,hasBLSKey:false,hasEIAKey:false,hasTwelveDataKey:false};
const runtime={status:'running',mode:'live',message:'Runtime active',quotes,bars:barMap,history:{},fundamentals:{AAA:{revenueGrowth:20,epsGrowth:22,roe:25,netMargin:18,debtToEquity:40}},news:[],earnings:[],filings:[],secIntelligence:{},scanner:{mode:'day',status:'idle',message:'Ready',results:[]},lastUpdated:{quotes:now,'quotes-rest':now,'alpaca-stream':now,'alpaca-live':now,history:now,fundamentals:now,news:now,earnings:now,filings:now,'cache-refresh':now,scanner:now,vix:now,ai:now},health:{quotes:'streaming','quotes-rest':'Healthy','alpaca-stream':'IEX connected · 25-symbol fallback pool','alpaca-live':'Idle · market closed',history:'7797 bars · desk-scoped',fundamentals:'Healthy',news:'Healthy',earnings:'Healthy',filings:'Healthy · SEC EDGAR','cache-refresh':'healthy · manual',scanner:'Idle',vix:'Healthy',ai:'Ready'},feed:{marketSession:'regular',feedState:'streaming',webSocketConnected:true,subscribedSymbols:['AAA'],alpacaWebSocketConnected:true,alpacaSubscribedSymbols:['SPY','QQQ'],lastTradeAt:now,lastTradeSymbol:'AAA',lastAlpacaStreamAt:now,lastAlpacaStreamSymbol:'SPY',lastAlpacaAt:now,lastAlpacaSymbol:'SPY',alpacaLiveFeed:'iex',overnightDataMode:'auto',overnightLiveAvailable:false},global:{tone:'CONSTRUCTIVE',confidence:82,summary:'Constructive test context',drivers:{semiconductors:{state:'SUPPORTIVE',label:'Semiconductors',confidence:90,detail:'SMH live proxy'},taiwan:{state:'SUPPORTIVE',label:'Taiwan',confidence:80,detail:'EWT live proxy'}}},macroMetrics:{},macroEvents:[],eventMode:{active:false},eventReactions:[],options:{AAA:{symbol:'AAA',provider:'Alpaca Options',feed:'OPRA',state:'CURRENT',bias:'BULLISH',callVolume:1000,putVolume:500,putCallVolume:.5,averageIv:.35,expectedMove:8,updatedAt:now,provenance:'REAL OPTIONS SNAPSHOT'}},capabilities:[{capability:'Options Intelligence',source:'Alpaca Options',mode:'AUTO',status:'ACTIVE'}],signalValidation:{snapshots:[],message:'test'}};
L.setState(state,runtime);
const pc=L.priceContext('AAA');assert.equal(pc.live,130);assert.equal(pc.close,129.5);assert.equal(pc.prev,128);assert.equal(pc.closeLabel,'TODAY CLOSE');assert(Number.isFinite(L.planFor('AAA','swing').score));
assert.equal(L.quoteState('AAA').label,'LIVE');runtime.feed.marketSession='after-hours';assert.equal(L.quoteState('AAA').label,'AFTER-HOURS LIVE');runtime.feed.marketSession='closed';assert.equal(L.quoteState('AAA').label,'LAST TRADE');runtime.feed.marketSession='regular';
assert.equal(L.sessionLabel('pre-market'),'PRE-MARKET');assert.equal(L.sessionLabel('regular'),'MARKET OPEN');assert.equal(L.sessionLabel('after-hours'),'AFTER-HOURS');assert.equal(L.sessionLabel('overnight'),'OVERNIGHT');
assert.equal(L.headerDataHealth().label,'DATA HEALTHY');runtime.feed.feedState='finnhub-fallback';assert.equal(L.headerDataHealth().label,'PROVIDER DEGRADED');runtime.feed.feedState='streaming';

// v14.3.1 cross-module contextual intelligence must affect readiness/research without touching Setup Score.
const frozenScore=L.planFor('AAA','day').score;runtime.liquidity={AAA:{state:'RISK',spreadPercent:1.2,quoteAgeMs:1000}};runtime.marketOpenFlags={AAA:['LIQUIDITY RISK']};runtime.marketOpenCheckpoint={state:'COMPLETE',runAt:now,premarket:{AAA:{gapPercent:3.2,rangePercent:4.1,volume:1800000}},optionsContexts:1,dayCandidates:1,swingContextChanges:['AAA'],longContextChanges:[]};runtime.catalystReactions={AAA:{symbol:'AAA',triggerType:'EARNINGS',state:'EXTREME VOLATILITY',movePercent:9.4,flags:['LIQUIDITY RISK']}};runtime.symbolIntelligence={AAA:{symbol:'AAA',consecutiveBeats:3,peers:['BBB','CCC'],recommendationTrend:'BULLISH'}};runtime.intelligence={rates:{label:'Rates State',state:'RISING',detail:'10Y rising',source:'FRED'},credit:{label:'Credit State',state:'HEALTHY',detail:'HY stable',source:'FRED'}};runtime.providerRegistry=[{provider:'Finnhub',capability:'Peer intelligence',status:'AVAILABLE',detail:'QA',uses:['Research']}];runtime.preparations={'pre-market-prep':{label:'Pre-Market Prep',state:'COMPLETE'},'market-open-prep':{label:'Market Open Prep',state:'COMPLETE'},'catalyst-watch':{label:'Earnings & Material Catalyst Watch',state:'REACTION'}};L.setState(state,runtime);const v143Ready=L.tradeReadiness('AAA','day');assert.equal(v143Ready.status,'CAUTION');assert(v143Ready.risks.some(x=>x.includes('Liquidity')||x.includes('LIQUIDITY')));assert.equal(L.planFor('AAA','day').score,frozenScore);assert(L.buildAIClientContext('AAA','day').catalystReaction);assert(L.contextLens('AAA','swing').includes('Provider Intelligence'));assert(L.renderMaintenance().includes('Feed Capability Registry')&&L.renderMaintenance().includes('Market Open Prep'));runtime.liquidity={};runtime.marketOpenFlags={};runtime.catalystReactions={};L.setState(state,runtime);

// v14.3.1 identity with the validated deterministic trading baseline preserved.
assert(htmlSource.includes(`DE.PULSE v${releaseVersion}`)&&!htmlSource.includes('WC ·')&&!htmlSource.includes('TEST ·')&&!htmlSource.includes('test-build-badge'));assert(rendererSource.includes('Application & Build Identity'));assert(mainSource.includes(`const appVersion = "${releaseVersion}"`)&&mainSource.includes(releaseBuild));
const sundayOvernight=Date.UTC(2026,7,10,0,0,0);assert(L.sessionBoundarySummary(sundayOvernight).includes('Sun 8 PM ET')&&L.sessionBoundarySummary(sundayOvernight).includes('5 PM PT'));
assert(cssSource.includes('.sidebar-scroll{position:relative;flex:1 1 auto;min-height:0;overflow-y:auto')&&cssSource.includes('.sidebar-scroll.is-scrolling'));assert(cssSource.includes('grid-template-columns:minmax(70px,38%) minmax(0,62%)'));assert(cssSource.includes('.engine-health-chip{box-sizing:border-box!important;min-width:max-content!important'));
assert(cssSource.includes('--brand-matte-green:#193d31')&&cssSource.includes('--brand-copper:#a86f49')&&cssSource.includes('--brand-silver:#c6cbd1'));assert(fs.existsSync('De-Pulse-approved-v13.2.7-master.png')&&fs.statSync('renderer/icon.png').size>500000&&fs.existsSync('platform-icons/DePulse.icns')&&fs.existsSync('platform-icons/DePulse.ico'));

// v14.3.1 restores the full detailed side-panel Data Engine without a disclosure row.
assert(htmlSource.includes('sidebar-data-engine')&&htmlSource.includes('id="engine-health-detail"')&&htmlSource.includes('id="engine-mode"')&&htmlSource.includes('id="health-list"'));
assert(!htmlSource.includes('sidebar-engine-details')&&!htmlSource.includes('data-jump="maintenance"'));
const healthKeys=L.sidebarHealthEntries(runtime.health).map(x=>x[0]);assert(healthKeys.includes('quotes')&&healthKeys.includes('vix')&&healthKeys.includes('ai'));
assert(L.sidebarHealthEntries({quotes:'Streaming'}).find(x=>x[0]==='vix')[1]==='Not initialized');assert(rendererSource.includes('sidebarHealthEntries(runtime?.health||{})'));
assert(!mainSource.includes('/api/maintenance/run')||mainSource.includes('handleMaintenanceRun'));assert(!mainSource.match(/duplicate.*subscription/i));

// Removed modules are hard-deleted from active application code/state/routes/UI.
for(const forbidden of ['ShowAlerts','ShowPortfolio','ShowJournal','showAlerts','showPortfolio','showJournal','handleAlertSave','handlePositionSave','handleJournalSave','/api/alerts/','/api/positions/','/api/journal/','renderOptional(','data-page="alerts"','data-page="portfolio"','data-page="journal"','Workspace Visibility'])assert(!mainSource.includes(forbidden)&&!rendererSource.includes(forbidden)&&!htmlSource.includes(forbidden),`removed module residue: ${forbidden}`);
assert(!/type\s+Alert\s+struct/.test(mainSource)&&!/type\s+Position\s+struct/.test(mainSource)&&!/type\s+JournalEntry\s+struct/.test(mainSource));

// Settings contains configuration only; maintenance owns diagnostics/storage/build.
const settings=L.renderSettings();assert(settings.includes('Configuration Summary')&&settings.includes('Core Market Data')&&settings.includes('Market Data Modes')&&settings.includes('Global, Macro & Options Data')&&settings.includes('SEC / Filing Configuration')&&settings.includes('Trading Engines')&&settings.includes('Signal Engine')&&settings.includes('AI Integration')&&settings.includes('Application')&&settings.includes('class="btn danger brand-quit"')&&settings.includes('quit-word'));assert(settings.includes('market-data-section')&&settings.includes('market-data-controls'));assert(!settings.includes('Add Ticker'));
for(const moved of ['Live Feed Diagnostics','Clear Market Cache','Cache Size','Permanent Watchlists','Workspace Visibility','Build</small>'])assert(!settings.includes(moved),`Settings still contains moved/removed content: ${moved}`);
assert(settings.includes('Save & Test')&&settings.includes('Overnight Data Mode')&&settings.includes('SEC Contact Email')&&settings.includes('Auto-Start Runtime'));
assert(settings.includes('Twelve Data · VIX / Global / History')&&settings.includes('Primary for VIX when configured · Global/History fallback')&&settings.includes('yfinance · Automatic Recovery')&&settings.includes('CBOE · VIX Validation')&&(settings.match(/No API key required/g)||[]).length>=2&&settings.includes('Configurable')&&settings.includes('Automatic'));

// Documentation + Maintenance are real pages and sidebar System destinations.
assert(htmlSource.includes('data-page="documentation"')&&htmlSource.includes('data-page="maintenance"')&&htmlSource.includes('data-nav-group="system"'));assert(htmlSource.includes('data-page="ai"'));assert(!htmlSource.includes('data-nav-group="ai"'));
const docs=L.renderDocumentation();assert(docs.includes('User Documentation')&&docs.includes('Developer Documentation')&&docs.includes('Capabilities &amp; Limitations'));
const maintenance=L.renderMaintenance();assert(maintenance.includes('Run Weekly Maintenance')&&maintenance.includes('Live Data Diagnostics')&&maintenance.includes('Data Engine Detail')&&maintenance.includes('Data & Storage')&&maintenance.includes('QA & Release History')&&maintenance.includes('Clear Market Cache'));
assert(mainSource.includes('func (a *Application) handleMaintenanceRun')&&mainSource.includes('maintenanceHealthStatus')&&mainSource.includes('MaintenanceLastRun'));assert(mainSource.includes('"/api/maintenance/run"'));
assert(fs.existsSync('renderer/docs/user.md')&&fs.existsSync('renderer/docs/developer.md')&&fs.existsSync('renderer/qa/manifest.json')&&fs.existsSync('renderer/qa/v13.3.0.txt'));

// Existing major functional areas and security/provider architecture remain intact.
assert(rendererSource.includes('Run Market Scan')&&rendererSource.includes('Discovery Watchlist'));assert(L.renderFilings().includes('Material Company Update')&&L.renderFilings().includes('Quarterly Report')&&L.renderFilings().includes('8-K')&&L.renderFilings().includes('10-Q'));assert(L.renderAI().includes('Research Confirmation')&&L.renderAI().includes('Manage AI')&&L.renderAI().includes('Research Target'));
assert(mainSource.includes('https://openrouter.ai/api/v1/chat/completions'));assert(mainSource.includes('wss://ws.finnhub.io')||mainSource.includes('finnhub.io'));assert(mainSource.includes('alpacaIEXPoolLimit'));assert(mainSource.includes('API keys are intentionally excluded'));
assert(rendererSource.includes('/api/app/open-url')&&rendererSource.includes('/api/app/quit'));assert(rendererSource.includes('fitHeaderNotification')&&rendererSource.includes('success:3800')&&rendererSource.includes('error:12500'));
assert(cssSource.includes('.documentation-shell')&&cssSource.includes('.maintenance-health-grid')&&cssSource.includes('.qa-history'));
assert(cssSource.includes('.doc-tabs{display:flex')&&cssSource.includes('position:relative;top:auto')&&!/\.doc-tabs\{[^}]*position:sticky/.test(cssSource));
assert(cssSource.includes('.maintenance-summary-grid{display:grid')&&rendererSource.includes('maintenanceTimePair')&&rendererSource.includes('Next recommended'));
assert((L.renderMaintenance().match(/maintenance-summary-panel/g)||[]).length>=3&&L.renderMaintenance().includes('maintenance-action-panel'));
assert(L.renderMaintenance().includes('Cache Activity')&&L.renderMaintenance().includes('Last updated')&&L.renderMaintenance().includes('Last cleared')&&L.renderMaintenance().includes('Latest five QA reports'));
assert(cssSource.includes('.main[data-page="settings"]{padding-bottom:18px!important}')&&cssSource.includes('--text-row-gap:6px'));
assert(settings.includes('Auto-Start Runtime')&&settings.includes('QUIT'));
assert(cssSource.includes('.app-brand-dot')&&cssSource.includes('align-items:center')&&L.renderMarkdown('# DE.PULSE Documentation').includes('app-brand-dot'));
const userDoc=fs.readFileSync('renderer/docs/user.md','utf8'),devDoc=fs.readFileSync('renderer/docs/developer.md','utf8');assert(!userDoc.includes('De.Pulse')&&!devDoc.includes('De.Pulse'));assert(userDoc.includes('DE.PULSE')&&devDoc.includes('DE.PULSE'));assert(L.brandInline('DE.PULSE').includes('app-brand-dot'));
const manifest=JSON.parse(fs.readFileSync('renderer/qa/manifest.json','utf8'));assert(manifest.releases.length>=8);assert.equal(manifest.releases[0].version,releaseVersion);assert(rendererSource.includes('qaManifest.slice(0,5)'),'stored QA history may grow; UI must independently bound visible recent history');assert(manifest.releases.every(x=>x.status&&x.date&&x.summary&&x.file));const qaFiles=fs.readdirSync('renderer/qa').filter(x=>/^v.*\.txt$/.test(x));assert(qaFiles.length>=13);assert(fs.existsSync('renderer/qa/v14.3.3-integration-placement-audit.md'));assert(fs.existsSync('renderer/qa/v15.1.2.txt'));
const maint=L.renderMaintenance();assert(maint.includes('Performance')&&maint.includes('Master Symbol Store')&&maint.includes('Run Weekly Maintenance'));
const deskHtml=L.renderDesk('swing');assert(deskHtml.includes('desk-watchlist-management')&&deskHtml.includes('watchlist-count-inline')&&deskHtml.includes('desk-add-row')&&deskHtml.includes('data-add-table-input="swing"')&&deskHtml.includes('id="desk-detail-swing"'));assert(!deskHtml.includes('Add Ticker'));assert((deskHtml.match(/Ticker symbol/g)||[]).length>=2);assert(rendererSource.includes("pendingDetailScroll")&&rendererSource.includes("scrollIntoView({behavior:'smooth',block:'start'})")&&rendererSource.includes("window.scrollTo({top:0,left:0,behavior:'auto'})"));assert(cssSource.includes('.desk-watchlist-management')&&cssSource.includes('.desk-add-row')&&cssSource.includes('.cache-activity-grid')&&cssSource.includes('.market-data-controls'));

L.resetDerivedCaches();const before=L.performanceSnapshot();const p1=L.planFor('AAA','swing'),p2=L.planFor('AAA','swing'),after=L.performanceSnapshot();assert(Math.abs(p1.score-p2.score)<1e-9);assert(after.analysis.swing.hits===before.analysis.swing.hits+1);assert(after.analysis.swing.misses===before.analysis.swing.misses+1);
runtime.quotes.AAA={...runtime.quotes.AAA,price:131,updatedAt:now+1000,providerTimestamp:now+1000};const misses=after.analysis.swing.misses;const p3=L.planFor('AAA','swing');assert(L.performanceSnapshot().analysis.swing.misses===misses+1);assert(p3.price===131);
assert.strictEqual(L.masterSymbolRecord('AAA').quote,runtime.quotes.AAA);assert.strictEqual(L.masterSymbolRecord('VIX'),null);assert.strictEqual(L.specialIndexRecord('VIX').store,'special-index');assert.strictEqual(L.symbolDataRecord('VIX').quote,runtime.quotes.VIX);const perfStore=L.performanceSnapshot();assert.equal(perfStore.specialIndexSymbols,1);assert(!Number.isNaN(perfStore.masterSymbols));assert(L.quoteAffectsPage('AAA','swing'));assert(!L.quoteAffectsPage('ZZZZ','swing'));assert(L.quoteAffectsPage('SPY','swing'));
runtime.feed.marketSession='pre-market';assert.equal(L.quoteState('AAA').label,'PRE-MARKET LIVE');runtime.feed.marketSession='after-hours';assert.equal(L.quoteState('AAA').label,'AFTER-HOURS LIVE');runtime.feed.marketSession='overnight';runtime.quotes.AAA={...runtime.quotes.AAA,dataState:'indicative',source:'alpaca-overnight-snapshot',providerTimestamp:Date.now()};assert.equal(L.quoteState('AAA').label,'INDICATIVE');runtime.feed.marketSession='regular';
assert(userDoc.startsWith('# DE.PULSE') && /User documentation/i.test(userDoc.split('\n')[0]));assert(devDoc.startsWith('# DE.PULSE') && /Developer documentation/i.test(devDoc.split('\n')[0]));assert(userDoc.length>7000&&devDoc.length>10000);for(const d of ['overall','feeds','stores','cache','desks','sessions','research'])assert(devDoc.includes(`[[diagram:${d}]]`)&&L.architectureDiagram(d).includes('doc-diagram'),`missing diagram ${d}`);assert(L.renderMarkdown('# DE.PULSE - User Documentation').includes('app-brand-inline'));assert(cssSource.includes('--brand-ivory:#d8c7a8')&&cssSource.includes('#main select{')&&cssSource.includes('background-image:linear-gradient(45deg'));assert(cssSource.includes('.brand-quit{display:inline-flex'));assert(L.brandInline('DE•PULSE').includes('app-brand-dot')&&L.brandInline('De.Pulse').includes('app-brand-dot'));
assert(htmlSource.includes('data-page="research"'));const researchHtml=L.renderResearch();assert(researchHtml.includes('Research Target')&&researchHtml.includes('Overview')&&researchHtml.includes('Earnings')&&researchHtml.includes('Fundamentals')&&researchHtml.includes('SEC & Ownership')&&researchHtml.includes('Catalysts')&&researchHtml.includes('Technical Context'));assert(researchHtml.includes('AI Second Opinion Ready')||researchHtml.includes('Research Refreshing')||researchHtml.includes('Research Evidence Incomplete'));assert(rendererSource.includes('v151ResearchReadyForAI')&&rendererSource.includes("toast(res.ready?'Research Ready':'Research Needs Review'"));assert(researchHtml.includes('research-target-grid'));
const dayCtx=L.contextMetrics('AAA','day'),swingCtx=L.contextMetrics('AAA','swing'),longCtx=L.contextMetrics('AAA','long');const labels=x=>x.map(v=>v[0]);assert.deepEqual(Array.from(labels(dayCtx.must)),['Session','Open Gap','VWAP','RVOL','Spread','Dollar Volume','ATR %']);assert.deepEqual(Array.from(labels(dayCtx.optional)),['RSI','EMA 9 / 21','Support / Resistance']);assert.deepEqual(Array.from(labels(swingCtx.must)),['Trend Structure','Relative Strength','ATR %','RVOL','Support / Resistance','Earnings']);assert.deepEqual(Array.from(labels(swingCtx.optional)),['RSI']);assert.deepEqual(Array.from(labels(longCtx.must)),['Revenue Growth','EPS Growth','Operating Margin','Free Cash Flow','Debt / Equity','P/E / Forward','SMA 50 / 200','Relative Strength']);assert.deepEqual(Array.from(labels(longCtx.optional)),['ROE','52W Position','Current Ratio','Dividend Yield']);assert(L.contextLens('AAA','day').includes('More context')&&L.contextLens('AAA','swing').includes('More context')&&L.contextLens('AAA','long').includes('More context'));assert(!L.contextLens('AAA','day').includes('<details class="context-more"'));
assert(L.renderDashboard().includes('Decision Queue')&&L.renderDashboard().includes('Catalyst Pulse')&&L.renderDiscovery().includes('Discovery Rank'));assert(rendererSource.includes('openResearch')&&rendererSource.includes("target==='research'"));assert(L.architectureDiagram('research').includes('Research Confirmation')&&!L.architectureDiagram('research').includes('Overview · Technicals'));
const ai=L.renderAI();assert(ai.includes('Research Confirmation')&&ai.includes('Research Target')&&ai.includes('Context is preloaded'));assert(rendererSource.includes('AI is advisory. It cannot trade, change Action/Score'));assert(mainSource.includes('FAVORABLE|MIXED|CAUTION|INFORMATIONAL')&&mainSource.includes('parseAIStructuredPayload'));
assert(!htmlSource.includes('data-page="news"')&&!htmlSource.includes('data-page="earnings"')&&!htmlSource.includes('data-page="filings"'));assert(rendererSource.includes('function renderNews')&&rendererSource.includes('function renderEarnings')&&rendererSource.includes('function renderFilings'));
const maintenance2=L.renderMaintenance();assert(maintenance2.includes('Freshness & Cache Policy')&&maintenance2.includes('Refresh Stale Data Now')&&maintenance2.includes('3:15–3:50 AM ET')&&maintenance2.includes('Run Integrity Check'));assert(mainSource.includes('/api/cache/refresh')&&mainSource.includes('preMarketPrepLoop')&&mainSource.includes('weeklyIntegrityLoop')&&mainSource.includes('runLowPriorityRefresh')&&mainSource.includes('sessionAwareHistoryLoop')&&mainSource.includes('sessionAwareSECLoop')&&mainSource.includes('sessionAwareEarningsLoop')&&mainSource.includes('autoFreshnessRecoveryLoop'));assert(/News\s+\[\]NewsItem/.test(mainSource)&&/SECIntelligence\s+map\[string\]SECIntelligenceSummary/.test(mainSource));
assert(fs.readFileSync('renderer/docs/user.md','utf8').includes('## Research Workspace'));assert(fs.readFileSync('renderer/docs/developer.md','utf8').includes('## Symbol Research Context Architecture'));
// v13.3.0 horizon intelligence: earnings, filings, AI context, and compact orchestration.
const isoToday=new Date().toISOString().slice(0,10), isoYesterday=new Date(Date.now()-86400000).toISOString().slice(0,10), isoTomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);
const epsActual=1.10,epsEstimate=1.00,revActual=1100,revEstimate=1000;
runtime.earnings=[{symbol:'AAA',date:isoYesterday,hour:'amc',epsActual,epsEstimate,revenueActual:revActual,revenueEstimate:revEstimate,quarter:2,year:2026},{symbol:'AAA',date:isoTomorrow,hour:'amc',epsEstimate:1.12,revenueEstimate:1200,quarter:3,year:2026}];
runtime.news=[{headline:'AAA raises guidance after earnings',summary:'Company raised outlook and increased guidance for the year.',source:'QA News',symbols:['AAA'],datetime:Math.floor(Date.now()/1000)}];
runtime.filings=[{id:'aaa-8k',symbol:'AAA',company:'AAA Corp',form:'8-K',filedAt:isoToday,description:'Material Company Update · guidance raised',meaning:'Material Company Update',category:'material',url:'https://example.com/8k'},{id:'aaa-10q',symbol:'AAA',company:'AAA Corp',form:'10-Q',filedAt:isoYesterday,description:'Quarterly Report',meaning:'Quarterly Report',category:'report',url:'https://example.com/10q'}];
runtime.secIntelligence={AAA:{symbol:'AAA',materialEvents:1,latestForm:'10-Q',latestFiledAt:isoYesterday,offeringRisk:'Low',signals:[]}};
const dayEpoch=d=>Math.floor(Date.parse(`${d}T20:00:00Z`)/1000);runtime.bars.AAA.daily=[{t:dayEpoch(new Date(Date.now()-2*86400000).toISOString().slice(0,10)),o:119,h:121,l:118,c:120,v:1000},{t:dayEpoch(isoYesterday),o:126,h:132,l:125,c:130,v:2200},{t:dayEpoch(isoToday),o:129,h:132,l:128,c:130,v:1800}];runtime.quotes.AAA={...runtime.quotes.AAA,price:130,updatedAt:Date.now(),providerTimestamp:Date.now(),source:'finnhub-websocket',dataState:'live'};runtime.lastUpdated={...runtime.lastUpdated,earnings:Date.now(),news:Date.now(),filings:Date.now(),fundamentals:Date.now()};L.setState(state,runtime);
const eIntel=L.earningsIntelligence('AAA');assert.equal(eIntel.guidance.status,'RAISED');assert.equal(eIntel.read,'STRONG');assert(L.earningsIntelligenceCard('AAA','swing').includes('Post-earnings reaction')&&L.earningsIntelligenceCard('AAA','swing').includes('Gap holding'));assert(L.earningsIntelligenceCard('AAA','long').includes('Earnings Trend'));assert(!L.earningsIntelligenceCard('AAA','day').includes('Reports AMC'));assert.equal(L.daysUntilDate(isoTomorrow),1);
assert(L.secHorizonCard('AAA','day').includes('Catalyst · SEC Filing')&&L.secHorizonCard('AAA','day').includes('Material Company Update'));assert(L.secHorizonCard('AAA','swing').includes('Filing / Catalyst Risk'));assert(L.secHorizonCard('AAA','long').includes('SEC Intelligence Summary'));assert(L.renderFilings().includes('Quarterly Report')&&L.renderFilings().includes('Material Company Update'));
const aiDay=L.buildAIClientContext('AAA','day'),aiLong=L.buildAIClientContext('AAA','long');assert(aiDay.deterministic&&aiDay.context&&aiDay.horizon==='day');assert(aiLong.deterministic&&aiLong.context&&aiLong.horizon==='long');assert.notDeepEqual(Array.from(aiDay.context),Array.from(aiLong.context));assert(rendererSource.includes("openAIFor(sym,origin='research',horizon='none',autoRun=true)")&&rendererSource.includes("data-research-ai")&&rendererSource.includes("aiAutoRun"));assert(rendererSource.includes("aiState.label==='AI Second Opinion Ready'||aiState.label==='Refresh AI Opinion'"),'automatic Research AI must skip duplicate calls when evidence/opinion is current');assert(rendererSource.includes('Raw quote ticks and successful')&&rendererSource.includes('Math.round(num(p.score)/5)*5'),'AI evidence freshness must be material-change driven rather than raw-tick driven');assert(L.renderAI().includes('Research Target')&&L.renderAI().includes('Optional question'));
const dash1330=L.renderDashboard();assert(dash1330.includes('Decision Queue')&&dash1330.includes('Catalyst Pulse')&&dash1330.includes('Why?')&&dash1330.includes('Options Intelligence')&&dash1330.includes('Market Intelligence'));assert(dash1330.includes('Material Company Update')||dash1330.includes('SEC'));
const policy1330=L.cacheRefreshPolicyMarkup();assert(policy1330.includes('3:15–3:50 AM ET')&&policy1330.includes('Saturday')&&policy1330.includes('24h + event invalidation')&&policy1330.includes('5m regular')&&policy1330.includes('15m active')&&policy1330.includes('Run Pre-Market Prep Now')&&policy1330.includes('Run Integrity Check'));
assert(cssSource.includes('.v14-cross-context')&&cssSource.includes('.research-target-controls select')&&cssSource.includes('background-image:linear-gradient(45deg,transparent 50%,#93a7bd 50%),linear-gradient(135deg,#93a7bd 50%,transparent 50%)'));
assert(rendererSource.includes('event-data-context-card')&&rendererSource.includes('data-source-context-row')&&rendererSource.includes('quoteAgeMs(p.sym)>1800000'));assert(cssSource.includes('v14.3.3')&&cssSource.includes('ticker-tape.ticker-scrolling .ticker-viewport:hover .ticker-track')&&cssSource.includes('.sec-intel-row b{font-size:9.8px'));assert(L.renderDashboard().includes('Market Intelligence')&&L.renderDashboard().includes('Options Intelligence'));assert(L.renderMarketIntelligence().includes('Global Market Drivers'));assert(L.renderSettings().includes('Global, Macro & Options Data'));assert(L.renderMaintenance().includes('Data Capabilities')&&L.renderMaintenance().includes('Signal Validation'));
// v14.3.3 notification feedback lives inside the fixed-height global header center lane.
assert(htmlSource.includes('<div id="header-notification" class="header-notification"')&&htmlSource.indexOf('id="header-notification"')<htmlSource.indexOf('</header>'));
assert(rendererSource.includes("host.className=`header-notification ${inferred}`"));
assert(rendererSource.includes("host.className='header-notification'"));
assert(!cssSource.includes('.app-shell-toast{position:fixed!important'));
assert(cssSource.includes('v14.3.3 — live-data allocation + operational UX final overrides')&&cssSource.includes('text-overflow:ellipsis!important')&&rendererSource.includes('fitHeaderNotification'));
assert(rendererSource.includes('data-engine-action')&&rendererSource.includes('runDataEngineAction')&&rendererSource.includes('/api/data-engine/catalyst-evaluate')&&rendererSource.includes('/api/data-engine/capabilities-recheck'));
assert(!htmlSource.includes('data-engine-manual-actions'));assert(rendererSource.includes('maintenanceHealthCard')&&rendererSource.includes('maintenance-card-action'));
assert(rendererSource.includes('captureSaveContext')&&rendererSource.includes('restoreSaveContext(saveContext)'));
assert(rendererSource.includes('/api/cache/market-open-prep')&&rendererSource.includes('Run Market Open Prep Now'));
assert(rendererSource.includes('providerRegistryMarkup')&&rendererSource.includes('marketOpenFlags')&&rendererSource.includes('catalystReactions'));
assert(cssSource.includes('.always-visible-market-context .global-context-body{display:grid!important;gap:24px!important'));

assert(rendererSource.includes('Live Coverage State:')&&rendererSource.includes('vixDiagnosticsCard')&&rendererSource.includes('capabilities</span>')&&rendererSource.includes('discovery-rank-cell'));assert(cssSource.includes('.cache-policy-row span{font-size:12px')&&cssSource.includes('.capability-card>strong{font-size:11.5px'));assert(rendererSource.includes('liveCoverage:runtime?.liveCoverage')&&rendererSource.includes('Live Market Coverage'));assert(cssSource.includes('sidebar-prep-state')&&cssSource.includes('font-size:15px!important'));
// v14.3.5 baseline screenshot-regression fixes remain protected.
assert(rendererSource.includes('qaManifest.slice(0,5)'));
assert(rendererSource.includes('QA METADATA MISSING'));
assert(rendererSource.includes('data-expand-key="queue-${esc(p.sym)}-${p.deskKind}" open'));
assert(rendererSource.includes("if(k==='vix')return ['vix-refresh'"));
assert(rendererSource.includes('settings-autostart-control')&&rendererSource.includes("pageHead('Settings'"));
assert(rendererSource.includes('header-notification-text'));
assert(cssSource.includes('DE.PULSE v14.3.5 — focused UI refinement patch'));
assert(cssSource.includes('.cache-policy-row{min-height:0!important'));
assert(cssSource.includes('grid-template-areas:"head action" "value action" "time action"'));
assert(cssSource.includes('Maintenance actions: integrated mini-panel')&&cssSource.includes('.maintenance-card-action .engine-mini-action'));
assert(rendererSource.includes('autostart-state')&&rendererSource.includes('ACTIVE')&&cssSource.includes('Settings Auto-Start: premium status capsule'));

// v14.3.6 patch: SEC classification, membership visibility, regime SPY/QQQ, side-dot relocation and Discovery collision hardening.
assert(cssSource.includes('DE.PULSE v14.3.6 — SEC clarity, market-at-a-glance & Discovery QA patch'));
assert(cssSource.includes('DE.PULSE v14.3.7 — font-fit audit patch'));
assert(cssSource.includes('.scanner-number-cell{')&&cssSource.includes('font-size:11.5px!important')&&cssSource.includes('.event-data-context-head h3{')&&cssSource.includes('font-size:11px!important')); 
assert(rendererSource.includes('sidebar-prep-actionline')&&rendererSource.includes('button>${statusDot(tone(stateText)'));
assert(cssSource.includes('.sidebar-prep-actionline>.status-dot')&&cssSource.includes('width:6px!important'));
const membership=L.deskMembershipStrip('AAA');assert(membership.includes('DAY')&&membership.includes('SWING')&&membership.includes('LONG')&&(membership.match(/active/g)||[]).length===3);
const regime=L.deskRegimeControlGrid('swing');assert(regime.includes('regime-live-strip')&&regime.includes('>SPY<')&&regime.includes('>QQQ<')&&regime.includes('regime-direction-pill')&&regime.includes('Data Confidence'));assert(['STRONG BULLISH','BULLISH','LEAN BULLISH','NEUTRAL','LEAN BEARISH','BEARISH','STRONG BEARISH'].includes(L.regimeDirectionalState(L.marketRegimeFor('swing'))));
assert.equal(L.globalDriverSummaryText({tone:'NEUTRAL',summary:'NEUTRAL · 6 supportive / 3 headwind evidence points'}),'6 supportive / 3 headwind evidence points');assert.equal(L.globalDriverStateTone('CONSTRUCTIVE'),'green');
const scanRows=[{symbol:'AAA',price:25.5,score:86,changePercent:18.73,gapPercent:14.87,relativeVolume:.81,dollarVolume:6400000,spreadPercent:.15,reasons:['Tight current spread','Strong session move']}];
const scanMarkup=L.scannerTable('day',scanRows,new Set());assert(scanMarkup.includes('Liquidity / Spread')&&scanMarkup.includes('Desks')&&scanMarkup.includes('scanner-liquidity-cell')&&scanMarkup.includes('desk-membership-strip'));
assert(cssSource.includes('min-width:1320px!important')&&cssSource.includes('grid-template-columns:minmax(62px,.65fr)'));
assert(rendererSource.includes('compact-options-provider')&&cssSource.includes('.compact-options-provider')&&cssSource.includes('height:auto!important'));
const form4={form:'4',signal:'Buy',meaning:'Insider Buy',actor:'Jane Example',role:'CFO',transactionType:'Open-market/private purchase',shares:1000,price:25.5,value:25500,ownershipAfter:12000};assert.equal(L.secFilingMeaning(form4),'Insider BUY');assert(L.secFilingDetail(form4).includes('Open-market/private purchase')&&L.secFilingDetail(form4).includes('12,000 owned after'));
assert(rendererSource.includes("['4','Insider Buy / Sell / Other']"));assert(cssSource.includes('Decision Queue: the four compact headline values')&&cssSource.includes('.global-context-state')&&cssSource.includes('grid-template-columns:minmax(390px,640px)'));

assert.equal(L.ageText(42000),'42s');assert.equal(L.ageText(8*60000+12000),'8m 12s');assert.equal(L.ageText(2*3600000+14*60000),'2h 14m');assert.equal(L.ageText(3*86400000+4*3600000),'3d 4h');
// v15.1.2 Research v2, SEC detail, Data Freshness v2 and readiness surfaces.
const rOverview=L.researchOverview?L.researchOverview('AAA'):L.renderResearch();
assert(rOverview.includes('Research Decision Brief')&&rOverview.includes('What Changed Since Last Review')&&rOverview.includes('Risk Register'));
assert(L.researchEarningsV2('AAA').includes('Earnings Deep Dive'));
assert(L.researchFundamentals('AAA').includes('Fundamentals Interpretation')&&L.researchFundamentals('AAA').includes('Cash Generation'));assert(!L.researchFundamentals('AAA').includes('Leveraged'),'D/E 40 must not be misclassified as leveraged');
assert(L.researchSECAndOwnership('AAA').includes('SEC & Ownership')&&L.researchSECAndOwnership('AAA').includes('Last 30 Days')&&L.researchSECAndOwnership('AAA').includes('Insider / Role'));
assert(L.researchCatalysts('AAA').includes('Catalyst Timeline'));
assert(L.researchTechnicals('AAA').includes('Technical Context'));
assert(L.masterMarketSymbolsPanel().includes('data-master-add')&&L.masterMarketSymbolsPanel().includes('Add Symbol')&&L.masterMarketSymbolsPanel().includes('Tracked Symbols'));assert.strictEqual(L.diagnosticVisibilityForRole('USER'),false);assert.strictEqual(L.diagnosticVisibilityForRole('DEMO'),false);assert.strictEqual(L.diagnosticVisibilityForRole('ADMIN'),true);assert.strictEqual(L.diagnosticVisibilityForRole('OWNER'),true);
runtime.freshness=[{dataset:'News',state:'FRESH',provider:'Finnhub',ageMs:60000,checkAgeMs:60000,dataAgeMs:77*60000,providerTimestamp:now-77*60000,receivedAt:now-60000,expectedCadenceMs:300000,nextExpectedAt:now+240000,reason:'Successfully checked; no newer mapped article',fallback:'Marketaux',affected:['Research'],action:'news',freshnessBasis:'last successful news check',timestampBasis:'latest article publication'}];runtime.freshnessSummary={fresh:1,dueSoon:0,delayed:0,stale:0,error:0,unavailable:0,idle:0};L.setState(state,runtime);const freshnessMarkup=L.dataFreshnessV15Markup();assert(freshnessMarkup.includes('Check Age')&&freshnessMarkup.includes('Data Age')&&freshnessMarkup.includes('Reason / Fallback')&&freshnessMarkup.includes('Successfully checked; no newer mapped article'));
assert.equal(L.ageText(42000),'42s');assert.equal(L.ageText(492000),'8m 12s');assert.equal(L.ageText((2*60+14)*60000),'2h 14m');assert.equal(L.ageText((3*24+4)*3600000),'3d 4h');
assert(L.tradingReadinessJobsMarkup().includes('Trading Readiness')&&L.renderMaintenance().includes('Data Freshness v2'));
assert(rendererSource.includes('v151SelectResearchTarget')&&rendererSource.includes('/api/research/refresh')&&rendererSource.includes("researchAiMode"));
assert(cssSource.includes('.v151-freshness-row')&&cssSource.includes('.sec-transaction-table-wrap')&&cssSource.includes('.research-target-grid'));
console.log('renderer logic + v15.1.2 stability/UI regression tests: PASS');
