const fs=require('fs'),vm=require('vm'),assert=require('assert');
const releaseIdentity=JSON.parse(fs.readFileSync('release_identity.json','utf8'));
const c={console,globalThis:{__DEPULSE_TEST__:true},document:{querySelector(){return null},querySelectorAll(){return []}},window:{addEventListener(){}},fetch:async()=>({ok:false,status:404,text:async()=>'',json:async()=>({})}),EventSource:function(){},ResizeObserver:function(){this.observe=()=>{}},setInterval(){},setTimeout,clearTimeout,requestAnimationFrame:f=>f()};c.globalThis=c;c.__DEPULSE_TEST__=true;vm.createContext(c);vm.runInContext(fs.readFileSync('renderer/renderer.js','utf8'),c);const L=c.DePulseLogic;
const now=Date.now();
function rising(n=120,start=120){return Array.from({length:n},(_,i)=>{const p=start+i*.7;return {o:p-.3,h:p+1,l:p-1,c:p,v:1000000+i*25000}})}
const b=rising(),last=b.at(-1).c;
const quotes={NVDA:{symbol:'NVDA',price:last,previousClose:last-3,open:last-2,changePercent:2,updatedAt:now,providerTimestamp:now,source:'finnhub-websocket',dataState:'live'},SPY:{price:600,changePercent:1.2,updatedAt:now,source:'finnhub-websocket',dataState:'live'},QQQ:{price:520,changePercent:1.5,updatedAt:now,source:'finnhub-websocket',dataState:'live'},IWM:{price:225,changePercent:1.1,updatedAt:now},XLK:{price:250,changePercent:1.4,updatedAt:now},TLT:{price:90,changePercent:-.5,updatedAt:now},GLD:{price:300,changePercent:-.2,updatedAt:now},SLV:{price:35,changePercent:0,updatedAt:now},USO:{price:80,changePercent:.2,updatedAt:now},VIX:{price:15,changePercent:-6,updatedAt:now,source:'vix-index',dataState:'live'}};
const bars={};for(const s of Object.keys(quotes))bars[s]={daily:b,intraday:b,weekly:b.filter((_,i)=>i%5===0)};
const state={version:releaseIdentity.version,settings:{dataMode:'live',dayWatchlistId:'day',swingWatchlistId:'swing',longWatchlistId:'long',discoveryWatchlistId:'discovery',dayEnabled:true,swingEnabled:true,longEnabled:true},watchlists:[{id:'day',name:'Day',symbols:['NVDA']},{id:'swing',name:'Swing',symbols:['NVDA']},{id:'long',name:'Long',symbols:['NVDA']},{id:'discovery',name:'Discovery',symbols:[]}],ui:{selectedTicker:'NVDA',scopeType:'watchlist',watchlistId:'day'}};
function freshRuntime(){return {status:'running',mode:'live',quotes:JSON.parse(JSON.stringify(quotes)),bars,history:{},fundamentals:{NVDA:{revenueGrowth:25,epsGrowth:30,operatingMargin:28,freeCashFlow:2e10,debtToEquity:20}},news:[],earnings:[],filings:[],secIntelligence:{},scanner:{mode:'day',status:'ready',results:[],radar:{status:'ACTIVE',session:'regular',promotions:[],candidates:[]}},lastUpdated:{quotes:now,history:now,fundamentals:now,news:now,earnings:now,filings:now,vix:now},health:{},feed:{marketSession:'regular',feedState:'streaming',webSocketConnected:true,subscribedSymbols:['NVDA']},global:{tone:'CONSTRUCTIVE',confidence:85,drivers:{}},macroMetrics:{},macroEvents:[],eventMode:{active:false},eventReactions:[],options:{},capabilities:[],signalValidation:{snapshots:[]},marketIntelligence:{tradeability:{state:'NORMAL'},relativeStrength:[]},liveCoverage:{NVDA:{state:'FINNHUB LIVE',provider:'Finnhub'}},liquidity:{NVDA:{state:'NORMAL',spreadPercent:.08}}};}
// 1. Fresh evidence may be READY in a clean fixture.
let runtime=freshRuntime();L.setState(state,runtime);const frozenScore=L.planFor('NVDA','day').score;assert.equal(L.quoteState('NVDA').label,'LIVE');assert.equal(L.tradeReadiness('NVDA','day').status,'READY');
// 2. A stale live-provider quote must never remain READY for a Day entry.
runtime=freshRuntime();runtime.quotes.NVDA.updatedAt=now-10*60*1000;runtime.quotes.NVDA.providerTimestamp=now-10*60*1000;L.setState(state,runtime);assert.equal(L.quoteState('NVDA').label,'STALE');let r=L.tradeReadiness('NVDA','day');assert.equal(r.status,'INCOMPLETE');assert(r.risks.some(x=>/stale/i.test(x)));assert.equal(L.planFor('NVDA','day').score,frozenScore,'freshness safety must not mutate deterministic score');
// 3. Market-level degraded truth blocks readiness even if the ticker quote itself is fresh.
runtime=freshRuntime();runtime.marketIntelligence.tradeability={state:'DATA DEGRADED'};L.setState(state,runtime);r=L.tradeReadiness('NVDA','day');assert.equal(r.status,'INCOMPLETE');assert(r.risks.some(x=>/DATA DEGRADED/.test(x)));
// 4. Wide/risky liquidity becomes CAUTION, never READY.
runtime=freshRuntime();runtime.liquidity.NVDA={state:'RISK',spreadPercent:1.4,detail:'wide spread'};L.setState(state,runtime);r=L.tradeReadiness('NVDA','day');assert.equal(r.status,'CAUTION');assert(r.risks.some(x=>/Liquidity/i.test(x)));
// 5. A high-impact event makes Day readiness CAUTION without changing the protected score.
runtime=freshRuntime();runtime.eventMode={active:true,name:'CPI',countdownS:600};L.setState(state,runtime);r=L.tradeReadiness('NVDA','day');assert.equal(r.status,'CAUTION');assert(r.risks.some(x=>/macro event/i.test(x)));assert.equal(L.planFor('NVDA','day').score,frozenScore);
// 6. Closed-market Day context cannot look like a live-ready entry.
runtime=freshRuntime();runtime.feed.marketSession='closed';runtime.feed.feedState='stopped';L.setState(state,runtime);assert.equal(L.quoteState('NVDA').label,'LAST TRADE');r=L.tradeReadiness('NVDA','day');assert.notEqual(r.status,'READY');assert(r.risks.some(x=>/closed/i.test(x)));
// 7. Community evidence is contextual/untrusted and never changes protected plan score.
runtime=freshRuntime();runtime.alternativeIntelligence={community:{state:'ELEVATED',items:[{symbol:'NVDA',platform:'TELEGRAM',source:'Watcher Guru',text:'rumor',trustState:'UNTRUSTED'}]}};L.setState(state,runtime);assert.equal(L.planFor('NVDA','day').score,frozenScore);
// 8. Opportunity Radar copy remains decision support/no execution and Shadow remains explicit.
runtime=freshRuntime();runtime.scanner.radar={status:'ACTIVE',session:'regular',scanned:500,promotions:[{symbol:'NVDA'}],candidates:[{symbol:'NVDA',opportunityScore:88,sessionRelativeVolume:3.2,rangeExpansion:2.1,changePercent:5.4,spreadPercent:.08,dollarVolume:100000000,priceConfirmation:'Confirmed'}],productionFloor:78,shadowFloor:72};runtime.shadowControl={promotionPath:'SHADOW → VALIDATED → APPROVED → PRODUCTION',experiments:[{key:'radar',stage:'SHADOW',canMutateProduction:false}]};L.setState(state,runtime);const radar=L.opportunityRadarMarkup();assert(/Decision support only/.test(radar));assert(/no execution/i.test(radar));assert(/Shadow control/i.test(radar));
console.log('v16.11 professional trader/investor real-money acceptance: PASS · stale/degraded/liquidity/event/closed-market/community/Radar truth');
