const fs=require('fs'),vm=require('vm'),assert=require('assert');
const context={console,globalThis:{__DEPULSE_TEST__:true},document:{querySelector(){return null},querySelectorAll(){return []}},window:{addEventListener(){}},fetch:async()=>({ok:false,status:404,text:async()=>'',json:async()=>({})}),EventSource:function(){},ResizeObserver:function(){this.observe=()=>{}},setInterval(){},setTimeout,clearTimeout,requestAnimationFrame:f=>f()};
context.globalThis=context;context.__DEPULSE_TEST__=true;vm.createContext(context);vm.runInContext(fs.readFileSync('renderer/renderer.js','utf8'),context);
const L=context.DePulseLogic;
const sec=s=>Math.floor(Date.parse(s)/1000), ms=s=>Date.parse(s);
const cutoff=ms('2026-06-15T12:00:00Z');
function series(base=100){const out=[];for(let i=0;i<80;i++){const t=sec(`2026-03-${String((i%28)+1).padStart(2,'0')}T20:00:00Z`)+Math.floor(i/28)*31*86400;const c=base+i*.2;out.push({t,o:c-.2,h:c+.5,l:c-.5,c,v:1000000+i*1000})}out.push({t:Math.floor((cutoff+86400000)/1000),o:150,h:155,l:145,c:152,v:2000000});return out.sort((a,b)=>a.t-b.t)}
const state={settings:{earningsPenalty:10,signalProfile:'balanced',marketContext:15},watchlists:[],ui:{selectedTicker:'AAA'}};
const bars={AAA:{daily:series(100),intraday:series(100),weekly:series(100)},SPY:{daily:series(500),intraday:series(500),weekly:series(500)},QQQ:{daily:series(400),intraday:series(400),weekly:series(400)},IWM:{daily:series(200),intraday:series(200),weekly:series(200)},XLK:{daily:series(220),intraday:series(220),weekly:series(220)},VIX:{daily:series(20),intraday:series(20),weekly:series(20)}};
const quotes={};for(const [sym,sets] of Object.entries(bars)){const b=sets.daily.at(-1);quotes[sym]={price:b.c,open:b.o,high:b.h,low:b.l,previousClose:sets.daily.at(-2).c,changePercent:1,updatedAt:cutoff+86400000,providerTimestamp:cutoff+86400000,source:'current-live',dataState:'live'}}
const runtime={mode:'live',status:'running',bars,quotes,feed:{marketSession:'regular',feedState:'streaming',subscribedSymbols:['AAA'],alpacaSubscribedSymbols:['SPY']},liveCoverage:{AAA:{state:'LIVE'}},scanner:{mode:'discovery',status:'complete',results:[{symbol:'AAA',score:99}]},health:{quotes:'live'},global:{tone:'CONSTRUCTIVE',confidence:99,drivers:{europe:{state:'SUPPORTIVE',confidence:99}}},options:{AAA:{bias:'BULLISH'},SPY:{bias:'BULLISH'}},marketIntelligence:{tradeability:{state:'TRADE NORMALLY'}},eventIntelligence:{marketRisk:{state:'LOW'}},researchPackage:{state:'READY'},evidenceSnapshot:{id:'CURRENT-EVIDENCE'},providerReconciliation:[{capability:'quotes'}],freshness:[{dataset:'Quotes'}],freshnessSummary:{fresh:1},signalValidation:{snapshots:[{id:'current'}]},validationLearning:{replayState:'CURRENT'},marketOpenFlags:{AAA:['CURRENT FLAG']},marketOpenCheckpoint:{state:'COMPLETE'},catalystReactions:{AAA:{state:'CURRENT'}},liquidity:{AAA:{state:'NORMAL'}},eventMode:{active:true},fundamentals:{AAA:{revenueGrowth:30,epsGrowth:25,roe:20,netMargin:15,debtToEquity:20,updatedAt:cutoff+1000}},news:[{headline:'Before',datetime:Math.floor((cutoff-1000)/1000)},{headline:'After',datetime:Math.floor((cutoff+1000)/1000)}],filings:[{id:'prior-day',symbol:'AAA',form:'8-K',filedAt:'2026-06-14'},{id:'same-day',symbol:'AAA',form:'10-Q',filedAt:'2026-06-15'},{id:'exact-time',symbol:'AAA',form:'8-K',filedAt:'2026-06-15T12:00:00Z'}],macroEvents:[{id:'before',name:'Before',startsAt:cutoff-1000,updatedAt:cutoff-500},{id:'cpi-release',name:'CPI',startsAt:cutoff,updatedAt:cutoff},{id:'fomc-release',name:'FOMC',startsAt:cutoff+2000,updatedAt:cutoff+2000},{id:'after',name:'After',startsAt:cutoff+1000,updatedAt:cutoff+1000},{id:'late-correction',name:'Late correction',startsAt:cutoff-5000,updatedAt:cutoff+1000}],eventReactions:[{eventId:'before',capturedAt:cutoff-500},{eventId:'after',capturedAt:cutoff+500}],earnings:[{symbol:'AAA',date:'2026-06-15',hour:'amc',epsActual:2.5,epsEstimate:2.0,revenueActual:200,revenueEstimate:180}]};
L.setState(state,runtime);
const liveBefore=L.planFor('AAA','swing');
const rr=L.replayRuntimeAt(cutoff,'swing');
assert(rr.bars.AAA.daily.every(b=>b.t*1000<cutoff),'future/incomplete bars leaked into replay');
assert.deepEqual(Object.keys(rr.marketIntelligence),[]);assert.deepEqual(Object.keys(rr.eventIntelligence),[]);assert.deepEqual(Object.keys(rr.options),[]);assert.equal(rr.global.tone,'UNAVAILABLE');
assert.equal(rr.feed.marketSession,'closed');assert.equal(rr.feed.feedState,'historical-replay');assert.deepEqual(Object.keys(rr.liveCoverage),[]);assert.equal(rr.scanner.results.length,0);assert.deepEqual(Object.keys(rr.health),[]);
assert.equal(rr.evidenceSnapshot.id,undefined);assert.equal(rr.signalValidation.snapshots.length,0);assert.equal(rr.earnings.length,0,'legacy replay must withhold earnings rows without knowledge timestamps');
assert.deepEqual(Array.from(rr.news.map(n=>n.headline)),['Before']);/* date-only SEC filing: a same-day filing after an intraday replay cutoff must be withheld when exact filing time is unknown. */assert.deepEqual(Array.from(rr.filings.map(f=>f.id)),['prior-day','exact-time'],'same-day date-only filing must not leak before exact filing time is known');assert.deepEqual(Array.from(rr.macroEvents.map(e=>e.id)),['before','cpi-release']);assert.deepEqual(Array.from(rr.eventReactions.map(e=>e.eventId)),['before']);assert.equal(rr.fundamentals.AAA,undefined);
const oneSecondBefore=cutoff-1000,pre=L.replayRuntimeAt(oneSecondBefore,'swing');assert(!pre.filings.some(f=>f.id==='exact-time'),'replay one second before SEC filing saw future filing');assert(!pre.macroEvents.some(e=>e.id==='cpi-release'),'replay one second before CPI saw release values');assert(!pre.macroEvents.some(e=>e.id==='fomc-release'),'replay before FOMC saw release values');assert(!pre.macroEvents.some(e=>e.id==='late-correction'),'later macro correction leaked backward');

const exact={symbol:'AAA',horizon:'swing',timestamp:cutoff,price:110,score:70,action:'EXTENDED',evidenceSnapshotId:'EV-1',formulaVersion:'deterministic-v14.3.7-compatible-v16.3',settingsFingerprint:'fp',earningsPenalty:10,earningsDays:20,familyScores:{Trend:70,Momentum:70,Participation:70,Structure:70,RelativeStrength:70,Market:70},entryLow:108,entryHigh:109,targetLow:120,targetHigh:125,invalidation:102,eventRisk:'LOW'};
const ex=L.replaySignalSnapshot(exact);assert.equal(ex.state,'EXACT');assert(Math.abs(ex.scoreDelta)<1e-9);assert.equal(ex.actionMatch,true);

const scenario={symbol:'AAA',horizon:'swing',timestamp:cutoff,price:110,score:50,action:'APPROACHING ENTRY',earningsPenalty:10,signalProfile:'balanced'};
const sc=L.replaySignalSnapshot(scenario);assert.equal(sc.state,'SCENARIO');assert(sc.detail.includes('present-day derived caches stripped'));

// Corporate-action cutoff safety: swing replay may reuse complete canonical raw daily history; without it replay must refuse as PARTIAL.
const rawDaily=bars.AAA.daily.map(b=>({...b,c:b.c*10,o:b.o*10,h:b.h*10,l:b.l*10}));runtime.bars.AAA['daily-raw']=rawDaily;runtime.corporateActionTruth={actions:[{symbol:'AAA',type:'forward_split',exDate:'2026-07-01',ratio:10,firstSeenAt:cutoff-1000,updatedAt:cutoff-1000}],rawHistoryCoverage:{AAA:{state:'COMPLETE',paginationComplete:true,barCount:rawDaily.length}}};runtime.corporateActions=runtime.corporateActionTruth.actions;L.setState(state,runtime);const rawReplay=L.replayRuntimeAt(cutoff,'swing');assert.equal(rawReplay._v163ReplayTruth.corporateAction.AAA.state,'RAW_HISTORY');assert.equal(rawReplay.bars.AAA.daily[0].c,rawReplay.bars.AAA['daily-raw']?.[0]?.c||rawReplay.bars.AAA.daily[0].c);runtime.corporateActionTruth.rawHistoryCoverage.AAA={state:'PARTIAL',paginationComplete:false,barCount:rawDaily.length};L.setState(state,runtime);const corpPartial=L.replaySignalSnapshot(scenario);assert.equal(corpPartial.state,'PARTIAL');assert(corpPartial.detail.includes('corporate-action adjustments'));
// Restore ordinary replay context for the final live-state restoration assertion.
runtime.corporateActionTruth={actions:[],rawHistoryCoverage:{}};runtime.corporateActions=[];delete runtime.bars.AAA['daily-raw'];L.setState(state,runtime);

const liveAfter=L.planFor('AAA','swing');assert.equal(liveAfter.score,liveBefore.score,'historical replay mutated live deterministic state');assert.equal(liveAfter.price,liveBefore.price,'historical replay mutated live quote state');
console.log('v16.3 renderer replay isolation tests: PASS');
