$ErrorActionPreference='Stop'
$R=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path; $S=Join-Path $R 'input\De-Pulse-v18.0.4-STABLE-Source.zip'; $SHA='a7fc226577a23ce89ad214183dfad73f11cde1e43b59eba08eedb200ddc0da2a'; $FP='9fa0e285cc90d7848aa7676a6169091a540601942f18422a31243b9ba6a8bee8'; $B='v18.0.4-stable-native-cross-platform-closure-20260813'; $O=Join-Path $R 'out\windows-x64'; $W=Join-Path $R '.work\windows-x64'; $E=Join-Path $O 'De-Pulse.exe'; $Z=Join-Path $O 'De-Pulse-v18.0.4-STABLE-Windows-x64.zip'
if((Get-FileHash -Algorithm SHA256 $S).Hash.ToLowerInvariant() -ne $SHA){throw 'source SHA mismatch'}; Remove-Item -Recurse -Force $O,$W -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path $O,(Join-Path $W 'src')|Out-Null; Expand-Archive -LiteralPath $S -DestinationPath (Join-Path $W 'src') -Force; Set-Location (Join-Path $W 'src')
if((python ci_pipeline.py --fingerprint).Trim() -ne $FP){throw 'source fingerprint mismatch'}; python v18_0_4_stable_promotion_gate.py; python v18_0_4_scope_gate.py; python v18_baseline_gate.py; go test -count=1 ./...; $env:CGO_ENABLED='0'; $env:GOOS='windows'; $env:GOARCH='amd64'; go build -trimpath -ldflags='-s -w' -o $E .; go version -m $E|Set-Content -Encoding utf8 (Join-Path $O 'windows-go-build-metadata.txt'); $M=Get-Content (Join-Path $O 'windows-go-build-metadata.txt') -Raw; if($M -notmatch 'GOOS=windows' -or $M -notmatch 'GOARCH=amd64'){throw 'Windows metadata mismatch'}
$env:APPDATA=Join-Path $W 'appdata'; $D=Join-Path $env:APPDATA 'PersonalMarketTerminal'; New-Item -ItemType Directory -Force -Path $D|Out-Null; $Sent=Join-Path $D 'g14-stable-sentinel.txt'; Set-Content -LiteralPath $Sent -Value "DE.PULSE-G14-STABLE-CONTINUITY`n" -Encoding ascii -NoNewline; $Sec=Join-Path $D 'secrets.json'; Set-Content -LiteralPath $Sec -Value '{"finnhub":"g14-finnhub","alpacaKey":"g14-alpaca-key","alpacaSecret":"g14-alpaca-secret"}' -Encoding utf8 -NoNewline; $SS=(Get-FileHash -Algorithm SHA256 $Sent).Hash.ToLowerInvariant(); $KS=(Get-FileHash -Algorithm SHA256 $Sec).Hash.ToLowerInvariant(); $Pwd='G14-'+[Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(24)).Replace('/','A').Replace('+','B').Replace('=','C'); $env:DEPULSE_HEADLESS='1'
function ReadLog([string]$P){if(Test-Path $P){return(Get-Content -LiteralPath $P -Raw -ErrorAction SilentlyContinue)};return ''}
function StartDep([string]$Phase){$script:I=Join-Path $D 'instance.json'; Remove-Item -LiteralPath $script:I -Force -ErrorAction SilentlyContinue; $so=Join-Path $O "$Phase.out"; $se=Join-Path $O "$Phase.err"; $script:P=Start-Process -FilePath $E -PassThru -RedirectStandardOutput $so -RedirectStandardError $se; $last=''; for($i=0;$i -lt 120;$i++){if($script:P.HasExited){throw "DE.PULSE exited before readiness ($Phase): $(ReadLog $se)"}; if(Test-Path $script:I){try{$u=(Get-Content $script:I -Raw|ConvertFrom-Json).url; if($u){$h=Invoke-RestMethod -Uri ($u+'api/health') -TimeoutSec 2; if($h.version -eq '18.0.4' -and $h.buildId -eq $B){$script:U=$u; return}}}catch{$last=$_.Exception.Message}}; Start-Sleep -Milliseconds 250}; throw "readiness timeout ($Phase): $last stderr=$(ReadLog $se)"}
function StopDep{if($script:P){Stop-Process -Id $script:P.Id -Force -ErrorAction SilentlyContinue; Wait-Process -Id $script:P.Id -ErrorAction SilentlyContinue; $script:P=$null}}
try{StartDep 'first'; $H=Invoke-RestMethod -Uri ($U+'api/health'); if($H.version -ne '18.0.4' -or $H.buildId -ne $B){throw 'runtime identity mismatch'}; if((Get-FileHash -Algorithm SHA256 $Sent).Hash.ToLowerInvariant() -ne $SS -or (Get-FileHash -Algorithm SHA256 $Sec).Hash.ToLowerInvariant() -ne $KS){throw 'Stable continuity file changed'}; $Danger=(Get-Acl $Sec).Access|Where-Object{$_.AccessControlType -eq 'Allow' -and $_.IdentityReference.Value -match '(?i)Everyone|ANONYMOUS LOGON' -and $_.FileSystemRights.ToString() -match '(?i)Write|Modify|FullControl'}; if($Danger){throw 'Stable secrets ACL grants broad write access'}; $S1=New-Object Microsoft.PowerShell.Commands.WebRequestSession; Invoke-WebRequest -Uri $U -WebSession $S1 -UseBasicParsing|Out-Null; $A=Invoke-RestMethod -Uri ($U+'api/auth/status') -WebSession $S1; if(-not $A.authenticated -or -not $A.bootstrapRequired -or $A.principal.role -ne 'OWNER'){throw 'bootstrap owner audit failed'}; $Db=Join-Path $D 'depulse-v17.db'; if(-not(Test-Path $Db)){throw 'SQLite database not created'}; $Csrf=$S1.Cookies.GetCookies([uri]$U)['depulse_csrf'].Value; if([string]::IsNullOrWhiteSpace($Csrf)){throw 'CSRF cookie missing'}; $Body=@{password=$Pwd}|ConvertTo-Json -Compress; Invoke-RestMethod -Method Post -Uri ($U+'api/auth/set-password') -WebSession $S1 -Headers @{'X-DE-PULSE-CSRF'=$Csrf} -ContentType 'application/json' -Body $Body|Out-Null; StopDep; Start-Sleep -Milliseconds 400; StartDep 'restart'; $S2=New-Object Microsoft.PowerShell.Commands.WebRequestSession; $Login=@{username='owner';password=$Pwd}|ConvertTo-Json -Compress; Invoke-RestMethod -Method Post -Uri ($U+'api/auth/login') -WebSession $S2 -ContentType 'application/json' -Body $Login|Out-Null; $A2=Invoke-RestMethod -Uri ($U+'api/auth/status') -WebSession $S2; if(-not $A2.authenticated -or $A2.bootstrapRequired -or $A2.principal.role -ne 'OWNER'){throw 'restart login failed'}; $Boot=Invoke-RestMethod -Uri ($U+'api/bootstrap') -WebSession $S2; if($Boot.runtime.providerRouter.policyVersion -ne 'smart-router-v2.0.0' -or $Boot.runtime.rapidMove.policyVersion -ne 'rapid-move-v1.0.0' -or $Boot.runtime.rapidMove.coverage.state -ne 'TIERED_PARTIAL'){throw 'runtime intelligence identity mismatch'}; if(-not(Test-Path $Db) -or (Get-FileHash -Algorithm SHA256 $Sent).Hash.ToLowerInvariant() -ne $SS -or (Get-FileHash -Algorithm SHA256 $Sec).Hash.ToLowerInvariant() -ne $KS){throw 'Stable persistence/continuity failed after restart'}}finally{StopDep}
@"
DE.PULSE v18.0.4 STABLE - Windows x64
Build ID: $B
G14 Stable canonical profile continuity + auth restart + Router/Rapid Move PASS.
"@|Set-Content -Encoding utf8 (Join-Path $O 'README.txt'); Compress-Archive -Path $E,(Join-Path $O 'README.txt') -DestinationPath $Z -Force; $ZS=(Get-FileHash -Algorithm SHA256 $Z).Hash.ToLowerInvariant(); $K=@('sourceSha','sourceFingerprint','nativeCompile','nativeSQLite','packageLauncherExecution','releaseIdentity','stableRuntimeContinuity','stableSecretsPreserved','bootstrapOwner','csrfPasswordSetup','restartPersistence','credentialLoginAfterRestart','smartRouterV2Runtime','rapidMoveRuntime','coverageTruth'); $Checks=[ordered]@{}; foreach($k in $K){$Checks[$k]=$true}; $Ev=[ordered]@{schemaVersion=1;gate='G14';status='PASS';release='v18.0.4 STABLE';buildId=$B;sourceSha256=$SHA;sourceFingerprint=$FP;platform='windows-x64';nativeArchitecture='amd64';checks=$Checks;artifact=@{name='De-Pulse-v18.0.4-STABLE-Windows-x64.zip';sha256=$ZS};generatedAt=[DateTime]::UtcNow.ToString('o')}; $Ev|ConvertTo-Json -Depth 10|Set-Content -Encoding utf8 (Join-Path $O 'g14-evidence.json'); Write-Host 'PASS: G14 Windows x64 v18.0.4 STABLE'
